name: Build and Test

on:
  push:
    branches: [ develop, main, feat/* ]
  pull_request:
    branches: [ develop, main, feat/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Run Tests
      run: mvn test